### ISSUE TITLE
Problème de compilation avec le strings.xml (packages/apps/Settings/res/values-fr/strings.xml)

### ISSUE THREAD

**Issue by NatsuDzn** [KowalskiOmniROM/DirtyUnicorns11FrenchTranslations#1]
Salut ! 
Il semble y avoir une erreur à la ligne 1712 (accessibility_screen_magnification_summary) du strings.xml empechant la compilation de la ROM

**Comment by KevinMinions** [comment]
Oui, je pensais l'avoir corrigé @NatsuDzn 
(C'est sur string.xml)
